# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.command.scraper.list:
    class: AppBundle\Command\ScraperListCommand
    arguments: ["@product.service", "@guzzle.client", "@crawler.service"]
    tags:
      -  { name: console.command }

  product.service:
    class: AppBundle\Service\Product

  guzzle.client:
    class: AppBundle\Service\ClientHttp

  crawler.service:
    class: AppBundle\Service\Crawler
    arguments: ["@crawler"]

  crawler:
    class: Symfony\Component\DomCrawler\Crawler